// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/form.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	OrderNumber   uint32                 `protobuf:"varint,2,opt,name=OrderNumber,proto3" json:"OrderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Question) GetOrderNumber() uint32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type Form struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Questions     []*Question            `protobuf:"bytes,3,rep,name=Questions,proto3" json:"Questions,omitempty"`
	Closed        bool                   `protobuf:"varint,4,opt,name=Closed,proto3" json:"Closed,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	AuthorID      string                 `protobuf:"bytes,5,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Form) Reset() {
	*x = Form{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{1}
}

func (x *Form) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Form) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Form) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Form) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Form) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Form) GetAuthorID() string {
	if x != nil {
		return x.AuthorID
	}
	return ""
}

func (x *Form) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RequestGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGet) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdate) Reset() {
	*x = RequestUpdate{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdate) ProtoMessage() {}

func (x *RequestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdate.ProtoReflect.Descriptor instead.
func (*RequestUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdate) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RequestDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDelete) Reset() {
	*x = RequestDelete{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelete) ProtoMessage() {}

func (x *RequestDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelete.ProtoReflect.Descriptor instead.
func (*RequestDelete) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{5}
}

func (x *RequestDelete) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=Form,proto3" json:"Form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{6}
}

func (x *RequestCreate) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type RequestGetMore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetMore) Reset() {
	*x = RequestGetMore{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetMore) ProtoMessage() {}

func (x *RequestGetMore) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetMore.ProtoReflect.Descriptor instead.
func (*RequestGetMore) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{7}
}

func (x *RequestGetMore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestGetMore) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Form          *Form                  `protobuf:"bytes,2,opt,name=Form,proto3" json:"Form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type GetMoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Forms         []*Form                `protobuf:"bytes,2,rep,name=Forms,proto3" json:"Forms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoreResponse) Reset() {
	*x = GetMoreResponse{}
	mi := &file_pkg_api_proto_form_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoreResponse) ProtoMessage() {}

func (x *GetMoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_form_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoreResponse.ProtoReflect.Descriptor instead.
func (*GetMoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_form_proto_rawDescGZIP(), []int{9}
}

func (x *GetMoreResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetMoreResponse) GetForms() []*Form {
	if x != nil {
		return x.Forms
	}
	return nil
}

var File_pkg_api_proto_form_proto protoreflect.FileDescriptor

const file_pkg_api_proto_form_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/api/proto/form.proto\"F\n" +
	"\bQuestion\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContent\x12 \n" +
	"\vOrderNumber\x18\x02 \x01(\rR\vOrderNumber\"\xc9\x01\n" +
	"\x04Form\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12'\n" +
	"\tQuestions\x18\x03 \x03(\v2\t.QuestionR\tQuestions\x12\x16\n" +
	"\x06Closed\x18\x04 \x01(\bR\x06Closed\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12\x1a\n" +
	"\bAuthorID\x18\x05 \x01(\tR\bAuthorID\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\"\x1c\n" +
	"\n" +
	"RequestGet\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"G\n" +
	"\rRequestUpdate\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\"0\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x1f\n" +
	"\rRequestDelete\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"*\n" +
	"\rRequestCreate\x12\x19\n" +
	"\x04Form\x18\x01 \x01(\v2\x05.FormR\x04Form\"8\n" +
	"\x0eRequestGetMore\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"O\n" +
	"\vGetResponse\x12%\n" +
	"\bResponse\x18\x01 \x01(\v2\t.ResponseR\bResponse\x12\x19\n" +
	"\x04Form\x18\x02 \x01(\v2\x05.FormR\x04Form\"U\n" +
	"\x0fGetMoreResponse\x12%\n" +
	"\bResponse\x18\x01 \x01(\v2\t.ResponseR\bResponse\x12\x1b\n" +
	"\x05Forms\x18\x02 \x03(\v2\x05.FormR\x05Forms2\xcc\x01\n" +
	"\vFormService\x12 \n" +
	"\x03Get\x12\v.RequestGet\x1a\f.GetResponse\x12,\n" +
	"\aGetMore\x12\x0f.RequestGetMore\x1a\x10.GetMoreResponse\x12#\n" +
	"\x06Update\x12\x0e.RequestUpdate\x1a\t.Response\x12#\n" +
	"\x06Delete\x12\x0e.RequestDelete\x1a\t.Response\x12#\n" +
	"\x06Create\x12\x0e.RequestCreate\x1a\t.ResponseB\x0eZ\f./pkg/api/pbb\x06proto3"

var (
	file_pkg_api_proto_form_proto_rawDescOnce sync.Once
	file_pkg_api_proto_form_proto_rawDescData []byte
)

func file_pkg_api_proto_form_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_form_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_form_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_form_proto_rawDesc), len(file_pkg_api_proto_form_proto_rawDesc)))
	})
	return file_pkg_api_proto_form_proto_rawDescData
}

var file_pkg_api_proto_form_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_api_proto_form_proto_goTypes = []any{
	(*Question)(nil),        // 0: Question
	(*Form)(nil),            // 1: Form
	(*RequestGet)(nil),      // 2: RequestGet
	(*RequestUpdate)(nil),   // 3: RequestUpdate
	(*Response)(nil),        // 4: Response
	(*RequestDelete)(nil),   // 5: RequestDelete
	(*RequestCreate)(nil),   // 6: RequestCreate
	(*RequestGetMore)(nil),  // 7: RequestGetMore
	(*GetResponse)(nil),     // 8: GetResponse
	(*GetMoreResponse)(nil), // 9: GetMoreResponse
}
var file_pkg_api_proto_form_proto_depIdxs = []int32{
	0,  // 0: Form.Questions:type_name -> Question
	1,  // 1: RequestCreate.Form:type_name -> Form
	4,  // 2: GetResponse.Response:type_name -> Response
	1,  // 3: GetResponse.Form:type_name -> Form
	4,  // 4: GetMoreResponse.Response:type_name -> Response
	1,  // 5: GetMoreResponse.Forms:type_name -> Form
	2,  // 6: FormService.Get:input_type -> RequestGet
	7,  // 7: FormService.GetMore:input_type -> RequestGetMore
	3,  // 8: FormService.Update:input_type -> RequestUpdate
	5,  // 9: FormService.Delete:input_type -> RequestDelete
	6,  // 10: FormService.Create:input_type -> RequestCreate
	8,  // 11: FormService.Get:output_type -> GetResponse
	9,  // 12: FormService.GetMore:output_type -> GetMoreResponse
	4,  // 13: FormService.Update:output_type -> Response
	4,  // 14: FormService.Delete:output_type -> Response
	4,  // 15: FormService.Create:output_type -> Response
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_form_proto_init() }
func file_pkg_api_proto_form_proto_init() {
	if File_pkg_api_proto_form_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_form_proto_rawDesc), len(file_pkg_api_proto_form_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_form_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_form_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_form_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_form_proto = out.File
	file_pkg_api_proto_form_proto_goTypes = nil
	file_pkg_api_proto_form_proto_depIdxs = nil
}
